<a href="https://colab.research.google.com/github/jiruneko/impress_language/blob/main/impress_language_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
torch.Tensor(2,3)

tensor([[ 1.5891e-42, -2.5595e-34, -3.0345e-34],
        [ 3.1496e-41,  7.0065e-45,  4.5090e-41]])

In [ ]:
torch.tensor(range(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.tensor([[0,1,2],[3,4,5]])

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
torch.arange(6).reshape(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
a = torch.arange(6).reshape(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
a.reshape(3,2)

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
a + 2

tensor([2, 3, 4, 5, 6, 7])

In [ ]:
a - 2

tensor([-2, -1,  0,  1,  2,  3])

In [ ]:
a = torch.arange(6).reshape(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
b = a + 1

In [ ]:
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
a0 = torch.arange(24).reshape(-1,2,4)
a1 = torch.arange(24).reshape(-1,4,2)
torch.bmm(a0,a1)

tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])

In [ ]:
a = torch.tensor([1.,2.,3.])
torch.sin(a)

tensor([0.8415, 0.9093, 0.1411])

In [ ]:
torch.log(a)

tensor([0.0000, 0.6931, 1.0986])

In [ ]:
a = torch.tensor([1,2,3])
torch.sin(a)

tensor([0.8415, 0.9093, 0.1411])